services:
  mvc:
    image: micro-mvc:dev
    container_name: micro-mvc
    restart: unless-stopped
    environment:
      - PDO_DB_STRING=mysql:host=database;dbname=test
      - PDO_DB_USER=test
      - PDO_DB_PASS=test
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80

  database:
    image: mariadb:11.3
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
